language: python
python:
    - "2.7"
    # - "3.4"
install:
    - pip install unrealcv
script:
    - py.test test/client
    # There is no way to test ipc and commands with travis, they need to be tested locally
    # Because travis can not run the UE4 binary.
